apiVersion: apps/v1
kind: Deployment
metadata:
  name: therabot-k3s
  namespace: development
  labels:
    app: therabot-k3s
    environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: therabot-k3s
  template:
    metadata:
      labels:
        app: therabot-k3s
    spec:
      containers:
        - name: therabot-k3s-container
          image: soham444/therabot:v1.0.0
          ports:
            - containerPort: 80   

          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "256Mi"

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80

            initialDelaySeconds: 5
            periodSeconds: 5          