apiVersion: apps/v1
kind: Deployment
metadata:
  name: therabot-k3s
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: therabot-k3s
  template:
    metadata:
      labels:
        app: therabot-k3s
    spec:
      containers:
        - name: therabot-k3s-container
          image: soham444/therabot:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "1Gi"       # TF needs more memory
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
          env:
            - name: PORT
              value: "8000"
            - name: WEB_CONCURRENCY
              value: "1"        # Single Gunicorn worker
            - name: MAX_REQUESTS
              value: "1000"
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5
